title: An attempt in pagemaking
author: bjn82
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm making a website!!!1!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
